import { getRequestConfig } from 'next-intl/server'
import { routing } from './routing'

/**
 * Load plugin translations from separate files using dynamic imports
 * Files are organized as: messages/plugins/{pluginId}/{locale}.json
 */
async function loadPluginMessages(locale: string): Promise<Record<string, any>> {
  const plugins: Record<string, any> = {}
  
  // List of known plugins - AUTO-GENERATED by generate-metadata.ts script
  // ⚠️  DO NOT EDIT MANUALLY - This list is updated automatically when you run: pnpm generate-metadata
  const knownPlugins = [
    '16personalities',
    'codeforces',
    'codewars',
    'duolingo',
    'github',
    'lastfm',
    'lyfta',
    'myanimelist',
    'stackoverflow',
    'steam',
  ]
  
  // Try to load each plugin's translation file
  await Promise.all(
    knownPlugins.map(async (pluginId) => {
      try {
        // Next.js/Webpack handles JSON imports - they're always default exports
        const pluginModule = await import(`../messages/plugins/${pluginId}/${locale}.json`)
        // JSON imports can be either .default or the object itself
        const pluginMessages = pluginModule.default || pluginModule
        if (pluginMessages && typeof pluginMessages === 'object') {
          plugins[pluginId] = pluginMessages
        }
      } catch (error: any) {
        // Plugin file doesn't exist yet or can't be loaded - skip silently
        // This is expected for new plugins that haven't been generated yet
      }
    })
  )
  
  return plugins
}

export default getRequestConfig(async ({ requestLocale }) => {
  // This typically corresponds to the `[locale]` segment
  let locale = await requestLocale

  // Ensure that a valid locale is used
  if (!locale || !routing.locales.includes(locale as any)) {
    locale = routing.defaultLocale
  }

  // Load base messages
  const baseMessages = (await import(`../messages/${locale}.json`)).default
  
  // Load plugin messages from separate files
  const pluginMessages = await loadPluginMessages(locale)
  
  // Merge plugin messages into main messages object
  const messages = {
    ...baseMessages,
    plugins: pluginMessages,
  }
  
  return {
    locale,
    messages,
  }
})


