/**
 * AUTOMATICALLY GENERATED TYPES
 * 
 * This file is automatically generated from PLUGINS_METADATA.
 * DO NOT edit manually. Run "pnpm generate-types" to regenerate.
 * 
 * Last generation: 2025-12-30T14:00:30.898Z
 */

/**
 * Union type of all available plugin names
 */
export type PluginName = "16personalities" | "codeforces" | "codewars" | "duolingo" | "github" | "lastfm" | "lyfta" | "myanimelist" | "spotify" | "stackoverflow" | "steam"

/**
 * Union type of all available categories
 */
export type PluginCategory = "coding" | "music" | "gaming" | "anime"

/**
 * Union type of section IDs per plugin
 */
export type PluginSectionIds = {
  ["16personalities"]: "personality"
  codeforces: "rating_rank" | "contests_participated" | "problems_solved" | "recent_submissions"
  codewars: "rank_honor" | "completed_kata" | "languages_proficiency" | "leaderboard_position"
  duolingo: "current_streak" | "total_xp" | "languages_learning"
  github: "profile" | "activity" | "repositories" | "favorite_languages" | "favorite_license" | "calendar" | "code_habits" | "starred_repositories" | "gists" | "stargazers" | "top_repositories" | "star_lists" | "notable_contributions" | "recent_activity" | "introduction" | "featured_repositories" | "sponsorships" | "sponsors" | "people" | "repository_contributors"
  lastfm: "recent_tracks" | "statistics" | "top_artists" | "top_albums" | "top_tracks"
  lyfta: "statistics" | "recent_workouts" | "exercises" | "overview" | "last_workout"
  myanimelist: "statistics" | "last_activity" | "statistics_simple" | "anime_bar" | "manga_bar" | "anime_favorites" | "manga_favorites" | "character_favorites" | "people_favorites"
  spotify: "recent_tracks" | "top_artists" | "top_tracks" | "currently_playing" | "playlists" | "profile"
  stackoverflow: "reputation" | "badges" | "answers_questions" | "tags_expertise"
  steam: "statistics" | "recent_games" | "top_games"
}

/**
 * Union type of essentialConfigKeys per plugin
 */
export type PluginEssentialConfigKeys = {
  ["16personalities"]: never
  codeforces: never
  codewars: never
  duolingo: never
  github: "pat"
  lastfm: "apiKey" | "username"
  lyfta: "apiKey"
  myanimelist: never
  spotify: never
  stackoverflow: never
  steam: "apiKey" | "steamId"
}

/**
 * Helper type to get section IDs from a plugin
 */
export type GetPluginSections<T extends PluginName> = PluginSectionIds[T]

/**
 * Helper type to get essentialConfigKeys from a plugin
 */
export type GetPluginEssentialKeys<T extends PluginName> = PluginEssentialConfigKeys[T]

/**
 * Helper type for specific plugin config
 */
export type PluginConfig<T extends PluginName> = {
  enabled: boolean
  sections: GetPluginSections<T>[]
  username?: string
  [key: string]: any
}

/**
 * Type guard to check if it's a valid plugin name
 */
export function isValidPluginName(name: string): name is PluginName {
  return name in ["16personalities","codeforces","codewars","duolingo","github","lastfm","lyfta","myanimelist","spotify","stackoverflow","steam"]
}

/**
 * Type guard to check if it's a valid category
 */
export function isValidCategory(category: string): category is PluginCategory {
  return ["coding","music","gaming","anime"].includes(category as PluginCategory)
}
