/**
 * AUTOMATICALLY GENERATED TYPES
 * 
 * This file is automatically generated from PLUGINS_METADATA.
 * DO NOT edit manually. Run "pnpm generate-types" to regenerate.
 * 
 * Last generation: 2025-12-02T23:00:28.257Z
 */

/**
 * Union type of all available plugin names
 */
export type PluginName = "16personalities" | "github" | "lastfm" | "myanimelist"

/**
 * Union type of all available categories
 */
export type PluginCategory = "coding" | "music" | "anime"

/**
 * Union type of section IDs per plugin
 */
export type PluginSectionIds = {
  ["16personalities"]: "personality"
  github: "profile" | "activity" | "repositories" | "favorite_languages" | "favorite_license" | "calendar" | "code_habits" | "starred_repositories" | "gists" | "stargazers" | "top_repositories" | "star_lists" | "notable_contributions" | "recent_activity" | "introduction" | "featured_repositories" | "sponsorships" | "sponsors" | "people" | "repository_contributors"
  lastfm: "recent_tracks" | "statistics" | "top_artists" | "top_albums" | "top_tracks"
  myanimelist: "statistics" | "last_activity" | "statistics_simple" | "anime_bar" | "manga_bar" | "anime_favorites" | "manga_favorites" | "character_favorites" | "people_favorites"
}

/**
 * Union type of essentialConfigKeys per plugin
 */
export type PluginEssentialConfigKeys = {
  ["16personalities"]: never
  github: "pat"
  lastfm: "apiKey" | "username"
  myanimelist: never
}

/**
 * Helper type to get section IDs from a plugin
 */
export type GetPluginSections<T extends PluginName> = PluginSectionIds[T]

/**
 * Helper type to get essentialConfigKeys from a plugin
 */
export type GetPluginEssentialKeys<T extends PluginName> = PluginEssentialConfigKeys[T]

/**
 * Helper type for specific plugin config
 */
export type PluginConfig<T extends PluginName> = {
  enabled: boolean
  sections: GetPluginSections<T>[]
  username?: string
  [key: string]: any
}

/**
 * Type guard to check if it's a valid plugin name
 */
export function isValidPluginName(name: string): name is PluginName {
  return name in ["16personalities","github","lastfm","myanimelist"]
}

/**
 * Type guard to check if it's a valid category
 */
export function isValidCategory(category: string): category is PluginCategory {
  return ["coding","music","anime"].includes(category as PluginCategory)
}
