#!/usr/bin/env tsx
/**
 * Gera tipos TypeScript a partir de PLUGINS_METADATA
 */

import { PLUGINS_METADATA } from "../src/plugins/metadata.js"
import { writeFileSync } from "fs"
import { join } from "path"
import { fileURLToPath } from "url"
import { dirname } from "path"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const outputPath = join(__dirname, "../src/plugins/generated-types.ts")

// Generate union type of plugin names
const pluginNames = Object.keys(PLUGINS_METADATA)
const pluginNamesType = pluginNames.map((name) => `"${name}"`).join(" | ")

// Generate union type of categories
const categories = [...new Set(Object.values(PLUGINS_METADATA).map((m) => m.category))]
const categoriesType = categories.map((cat) => `"${cat}"`).join(" | ")

/**
 * Verifica se um nome precisa usar notação de colchetes (começa com número ou contém caracteres especiais)
 */
const needsBracketNotation = (name: string): boolean => {
  return /^[0-9]/.test(name) || !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)
}

// Generate section types per plugin
const sectionsByPlugin = Object.entries(PLUGINS_METADATA)
  .map(([name, metadata]) => {
    const sectionIds = metadata.sections.map((s) => `"${s.id}"`).join(" | ")
    const keyNotation = needsBracketNotation(name) ? `[${JSON.stringify(name)}]` : name
    return `  ${keyNotation}: ${sectionIds || "never"}`
  })
  .join("\n")

// Generate essentialConfigKeys types per plugin
const essentialKeysByPlugin = Object.entries(PLUGINS_METADATA)
  .map(([name, metadata]) => {
    const keys = metadata.essentialConfigKeysMetadata.map((m) => `"${m.key}"`).join(" | ")
    const keyNotation = needsBracketNotation(name) ? `[${JSON.stringify(name)}]` : name
    return `  ${keyNotation}: ${keys || "never"}`
  })
  .join("\n")

const generatedTypes = `/**
 * AUTOMATICALLY GENERATED TYPES
 * 
 * This file is automatically generated from PLUGINS_METADATA.
 * DO NOT edit manually. Run "pnpm generate-types" to regenerate.
 * 
 * Last generation: ${new Date().toISOString()}
 */

/**
 * Union type of all available plugin names
 */
export type PluginName = ${pluginNamesType}

/**
 * Union type of all available categories
 */
export type PluginCategory = ${categoriesType}

/**
 * Union type of section IDs per plugin
 */
export type PluginSectionIds = {
${sectionsByPlugin}
}

/**
 * Union type of essentialConfigKeys per plugin
 */
export type PluginEssentialConfigKeys = {
${essentialKeysByPlugin}
}

/**
 * Helper type to get section IDs from a plugin
 */
export type GetPluginSections<T extends PluginName> = PluginSectionIds[T]

/**
 * Helper type to get essentialConfigKeys from a plugin
 */
export type GetPluginEssentialKeys<T extends PluginName> = PluginEssentialConfigKeys[T]

/**
 * Helper type for specific plugin config
 */
export type PluginConfig<T extends PluginName> = {
  enabled: boolean
  sections: GetPluginSections<T>[]
  username?: string
  [key: string]: any
}

/**
 * Type guard to check if it's a valid plugin name
 */
export function isValidPluginName(name: string): name is PluginName {
  return name in ${JSON.stringify(pluginNames)}
}

/**
 * Type guard to check if it's a valid category
 */
export function isValidCategory(category: string): category is PluginCategory {
  return ${JSON.stringify(categories)}.includes(category as PluginCategory)
}
`

writeFileSync(outputPath, generatedTypes, "utf-8")
console.log(`✅ Types generated at ${outputPath}`)

