/**
 * Generates TS modules embedding shared.css and the registered font files
 * as string constants, so they can be bundled directly into the JS output
 * (no filesystem access needed at runtime - required for Cloudflare Workers).
 *
 * Run after changing src/styles/shared.css or src/fonts/assets/**:
 *   pnpm --filter @weeb/weeb-plugins run generate-embedded-assets
 */

import { readFileSync, writeFileSync } from "fs"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"
import { fontRegistry } from "../src/fonts/registry.js"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const root = resolve(__dirname, "..")

const HEADER = "// Auto-generated by scripts/generate-embedded-assets.ts - do not edit manually\n"

// --- shared.css ---
const sharedCssPath = resolve(root, "src/styles/shared.css")
const sharedCss = readFileSync(sharedCssPath, "utf8")

writeFileSync(
  resolve(root, "src/styles/generated-shared-css.ts"),
  `${HEADER}export const SHARED_CSS = ${JSON.stringify(sharedCss)}\n`
)
console.log("✅ Generated src/styles/generated-shared-css.ts")

// --- fonts ---
const fontEntries = fontRegistry.map((font) => {
  const filePath = resolve(root, "src/fonts/assets", font.subfolder, font.file)
  const buffer = readFileSync(filePath)
  const dataUri = `data:font/woff2;base64,${buffer.toString("base64")}`
  const key = `${font.subfolder}/${font.file}`
  return [key, dataUri] as const
})

const fontDataObject = fontEntries
  .map(([key, dataUri]) => `  ${JSON.stringify(key)}: ${JSON.stringify(dataUri)},`)
  .join("\n")

writeFileSync(
  resolve(root, "src/fonts/generated-font-data.ts"),
  `${HEADER}export const FONT_DATA_URIS: Record<string, string> = {\n${fontDataObject}\n}\n`
)
console.log(`✅ Generated src/fonts/generated-font-data.ts (${fontEntries.length} fonts)`)
