import { faker } from "@faker-js/faker"
import {
  CharacterFavorites,
  FullMalAnimeResponse,
  MalFullMangaResponse,
  PeopleFavorites,
} from "../types/FavoritesResponse"
import { MalLastUpdatesResponse } from "../types/malLastUpdates"

const animeData: FullMalAnimeResponse[] = [
  {
    mal_id: 5081,
    url: "https://myanimelist.net/anime/5081/Bakemonogatari",
    image: "https://cdn.myanimelist.net/images/anime/11/75274l.jpg",
    title: "Bakemonogatari",
    title_english: "Bakemonogatari",
    title_japanese: "化物語",
    title_synonyms: ["Ghostory", "Monstory"],
    type: "TV",
    episodes: 15,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2009-07-03T00:00:00+00:00",
      to: "2010-06-25T00:00:00+00:00",
      prop: {
        from: {
          day: 3,
          month: 7,
          year: 2009,
        },
        to: {
          day: 25,
          month: 6,
          year: 2010,
        },
      },
      string: "Jul 3, 2009 to Jun 25, 2010",
    },
    score: 8.32,
    rank: 253,
    popularity: 94,
    synopsis:
      "Koyomi Araragi, a third-year high school student, manages to survive a vampire attack with the help of Meme Oshino, a strange man residing in an abandoned building. Though being saved from vampirism and now a human again, several side effects such as superhuman healing abilities and enhanced vision still remain. Regardless, Araragi tries to live the life of a normal student, with the help of his friend and the class president, Tsubasa Hanekawa.\n\nWhen fellow classmate Hitagi Senjougahara falls down the stairs and is caught by Araragi, the boy realizes that the girl is unnaturally weightless. Despite Senjougahara's protests, Araragi insists he help her, deciding to enlist the aid of Oshino, the very man who had once helped him with his own predicament.\n\nThrough several tales involving demons and gods, Bakemonogatari follows Araragi as he attempts to help those who suffer from supernatural maladies.\n\n[Written by MAL Rewrite],",
    year: 2009,
    genres: [
      {
        mal_id: 7,
        type: "anime",
        name: "Mystery",
        url: "https://myanimelist.net/anime/genre/7/Mystery",
      },
      {
        mal_id: 22,
        type: "anime",
        name: "Romance",
        url: "https://myanimelist.net/anime/genre/22/Romance",
      },
      {
        mal_id: 37,
        type: "anime",
        name: "Supernatural",
        url: "https://myanimelist.net/anime/genre/37/Supernatural",
      },
    ],
    themes: [
      {
        mal_id: 32,
        type: "anime",
        name: "Vampire",
        url: "https://myanimelist.net/anime/genre/32/Vampire",
      },
    ],
  },
  {
    mal_id: 1698,
    url: "https://myanimelist.net/anime/1698/Nodame_Cantabile",
    image: "https://cdn.myanimelist.net/images/anime/9/11986l.jpg",
    title: "Nodame Cantabile",
    title_english: "Nodame Cantabile",
    title_japanese: "のだめカンタービレ",
    title_synonyms: [],
    type: "TV",
    episodes: 23,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2007-01-12T00:00:00+00:00",
      to: "2007-06-15T00:00:00+00:00",
      prop: {
        from: {
          day: 12,
          month: 1,
          year: 2007,
        },
        to: {
          day: 15,
          month: 6,
          year: 2007,
        },
      },
      string: "Jan 12, 2007 to Jun 15, 2007",
    },
    score: 8.26,
    rank: 322,
    popularity: 783,
    synopsis:
      "Shinichi Chiaki is a first class musician whose dream is to play among the elites in Europe. Coming from a distinguished family, he is an infamous perfectionist—not only is he highly critical of himself, but of others as well. The only thing stopping Shinichi from leaving for Europe is his fear of flying. As a result, he's grounded in Japan.\n\nDuring his fourth year at Japan's top music university, Shinichi happens to meet Megumi Noda or, as she refers to herself, Nodame. On the surface, she seems to be an unkempt girl with no direction in life. However, when Shinichi hears Nodame play the piano for the first time, he is in awe of the kind of music she creates. Nevertheless, Shinichi is dismayed to discover that Nodame is his neighbor, and worse, she ends up falling head over heels in love with him.\n\n[Written by MAL Rewrite]",
    year: 2007,
    genres: [
      {
        mal_id: 4,
        type: "anime",
        name: "Comedy",
        url: "https://myanimelist.net/anime/genre/4/Comedy",
      },
      {
        mal_id: 22,
        type: "anime",
        name: "Romance",
        url: "https://myanimelist.net/anime/genre/22/Romance",
      },
    ],
  },
  {
    mal_id: 1535,
    url: "https://myanimelist.net/anime/1535/Death_Note",
    image: "https://cdn.myanimelist.net/images/anime/1079/138100l.jpg",
    title: "Death Note",
    title_english: "Death Note",
    title_japanese: "デスノート",
    title_synonyms: ["DN"],
    type: "TV",
    episodes: 37,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2006-10-04T00:00:00+00:00",
      to: "2007-06-27T00:00:00+00:00",
      prop: {
        from: {
          day: 4,
          month: 10,
          year: 2006,
        },
        to: {
          day: 27,
          month: 6,
          year: 2007,
        },
      },
      string: "Oct 4, 2006 to Jun 27, 2007",
    },
    score: 8.62,
    rank: 89,
    popularity: 2,
    synopsis:
      "Brutal murders, petty thefts, and senseless violence pollute the human world. In contrast, the realm of death gods is a humdrum, unchanging gambling den. The ingenious 17-year-old Japanese student Light Yagami and sadistic god of death Ryuk share one belief: their worlds are rotten.\n\nFor his own amusement, Ryuk drops his Death Note into the human world. Light stumbles upon it, deeming the first of its rules ridiculous: the human whose name is written in this note shall die. However, the temptation is too great, and Light experiments by writing a felon's name, which disturbingly enacts his first murder.\n\nAware of the terrifying godlike power that has fallen into his hands, Light—under the alias Kira—follows his wicked sense of justice with the ultimate goal of cleansing the world of all evil-doers. The meticulous mastermind detective L is already on his trail, but as Light's brilliance rivals L's, the grand chase for Kira turns into an intense battle of wits that can only end when one of them is dead.\n\n[Written by MAL Rewrite]",
    year: 2006,
    genres: [
      {
        mal_id: 37,
        type: "anime",
        name: "Supernatural",
        url: "https://myanimelist.net/anime/genre/37/Supernatural",
      },
      {
        mal_id: 41,
        type: "anime",
        name: "Suspense",
        url: "https://myanimelist.net/anime/genre/41/Suspense",
      },
    ],
    themes: [
      {
        mal_id: 40,
        type: "anime",
        name: "Psychological",
        url: "https://myanimelist.net/anime/genre/40/Psychological",
      },
    ],
  },
  {
    mal_id: 20785,
    url: "https://myanimelist.net/anime/20785/Mahouka_Koukou_no_Rettousei",
    image: "https://cdn.myanimelist.net/images/anime/11/61039l.jpg",
    title: "Mahouka Koukou no Rettousei",
    title_english: "The Irregular at Magic High School",
    title_japanese: "魔法科高校の劣等生",
    title_synonyms: [],
    type: "TV",
    episodes: 26,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2014-04-06T00:00:00+00:00",
      to: "2014-09-28T00:00:00+00:00",
      prop: {
        from: {
          day: 6,
          month: 4,
          year: 2014,
        },
        to: {
          day: 28,
          month: 9,
          year: 2014,
        },
      },
      string: "Apr 6, 2014 to Sep 28, 2014",
    },
    score: 7.38,
    rank: 2406,
    popularity: 139,
    synopsis:
      'In the dawn of the 21st century, magic, long thought to be folklore and fairy tales, has become a systematized technology and is taught as a technical skill. In First High School, the institution for magicians, students are segregated into two groups based on their entrance exam scores: "Blooms," those who receive high scores, are assigned to the First Course, while "Weeds" are reserve students assigned to the Second Course.\n\nMahouka Koukou no Rettousei follows the siblings, Tatsuya and Miyuki Shiba, who are enrolled in First High School. Upon taking the exam, the prodigious Miyuki is placed in the First Course, while Tatsuya is relegated to the Second Course. Though his practical test scores and status as a "Weed" show him to be magically inept, he possesses extraordinary technical knowledge, physical combat capabilities, and unique magic techniques—making Tatsuya the irregular at a magical high school.\n\n[Written by MAL Rewrite]',
    year: 2014,
    genres: [
      {
        mal_id: 1,
        type: "anime",
        name: "Action",
        url: "https://myanimelist.net/anime/genre/1/Action",
      },
      {
        mal_id: 10,
        type: "anime",
        name: "Fantasy",
        url: "https://myanimelist.net/anime/genre/10/Fantasy",
      },
      {
        mal_id: 22,
        type: "anime",
        name: "Romance",
        url: "https://myanimelist.net/anime/genre/22/Romance",
      },
      {
        mal_id: 24,
        type: "anime",
        name: "Sci-Fi",
        url: "https://myanimelist.net/anime/genre/24/Sci-Fi",
      },
    ],
  },
  {
    mal_id: 30831,
    url: "https://myanimelist.net/anime/30831/Kono_Subarashii_Sekai_ni_Shukufuku_wo",
    image: "https://cdn.myanimelist.net/images/anime/1895/142748l.jpg",
    title: "Kono Subarashii Sekai ni Shukufuku wo!",
    title_english: "KonoSuba: God's Blessing on This Wonderful World!",
    title_japanese: "この素晴らしい世界に祝福を！",
    title_synonyms: ["Give Blessings to This Wonderful World!"],
    type: "TV",
    episodes: 10,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2016-01-14T00:00:00+00:00",
      to: "2016-03-17T00:00:00+00:00",
      prop: {
        from: {
          day: 14,
          month: 1,
          year: 2016,
        },
        to: {
          day: 17,
          month: 3,
          year: 2016,
        },
      },
      string: "Jan 14, 2016 to Mar 17, 2016",
    },
    score: 8.1,
    rank: 510,
    popularity: 38,
    synopsis:
      "After dying a laughable and pathetic death on his way back from buying a game, high school student and recluse Kazuma Satou finds himself sitting before a beautiful but obnoxious goddess named Aqua. She provides the NEET with two options: continue on to heaven or reincarnate in every gamer's dream—a real fantasy world! Choosing to start a new life, Kazuma is quickly tasked with defeating a Demon King who is terrorizing villages. But before he goes, he can choose one item of any kind to aid him in his quest, and the future hero selects Aqua. But Kazuma has made a grave mistake—Aqua is completely useless!\n\nUnfortunately, their troubles don't end here; it turns out that living in such a world is far different from how it plays out in a game. Instead of going on a thrilling adventure, the duo must first work to pay for their living expenses. Indeed, their misfortunes have only just begun!\n\n[Written by MAL Rewrite]",
    year: 2016,
    genres: [
      {
        mal_id: 2,
        type: "anime",
        name: "Adventure",
        url: "https://myanimelist.net/anime/genre/2/Adventure",
      },
      {
        mal_id: 4,
        type: "anime",
        name: "Comedy",
        url: "https://myanimelist.net/anime/genre/4/Comedy",
      },
      {
        mal_id: 10,
        type: "anime",
        name: "Fantasy",
        url: "https://myanimelist.net/anime/genre/10/Fantasy",
      },
    ],
    themes: [
      {
        mal_id: 62,
        type: "anime",
        name: "Isekai",
        url: "https://myanimelist.net/anime/genre/62/Isekai",
      },
      {
        mal_id: 20,
        type: "anime",
        name: "Parody",
        url: "https://myanimelist.net/anime/genre/20/Parody",
      },
    ],
  },
  {
    mal_id: 3702,
    url: "https://myanimelist.net/anime/3702/Detroit_Metal_City",
    image: "https://cdn.myanimelist.net/images/anime/3/9853l.jpg",
    title: "Detroit Metal City",
    title_english: "Detroit Metal City",
    title_japanese: "デトロイト・メタル・シティ",
    title_synonyms: ["DMC"],
    type: "OVA",
    episodes: 12,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2008-08-08T00:00:00+00:00",
      to: "2008-10-28T00:00:00+00:00",
      prop: {
        from: {
          day: 8,
          month: 8,
          year: 2008,
        },
        to: {
          day: 28,
          month: 10,
          year: 2008,
        },
      },
      string: "Aug 8, 2008 to Oct 28, 2008",
    },
    score: 8.09,
    rank: 521,
    popularity: 1174,
    synopsis:
      "Dominating the world of indie music, Detroit Metal City (DMC) is a popular death metal band known for its captivatingly dark and crude style. Its extravagant lead singer, Johannes Krauser II, is especially infamous as a demonic being who has risen from the fiery pits of hell itself in order to bring the world to its knees and lord over all mortals—or at least that's what he's publicized to be.\n\nUnbeknownst to his many worshippers, Krauser II is just the alter ego of an average college graduate named Souichi Negishi. Although he is soft-spoken, peace-loving, and would rather listen to Swedish pop all day, he must participate in DMC's garish concerts in order to make ends meet. Detroit Metal City chronicles Negishi's hilarious misadventures as he attempts to juggle his hectic band life, a seemingly budding romance, and dealing with his incredibly obsessive and dedicated fans.\n\n[Written by MAL Rewrite]",
    year: 2008,
    genres: [
      {
        mal_id: 4,
        type: "anime",
        name: "Comedy",
        url: "https://myanimelist.net/anime/genre/4/Comedy",
      },
    ],
    themes: [
      {
        mal_id: 50,
        type: "anime",
        name: "Adult Cast",
        url: "https://myanimelist.net/anime/genre/50/Adult_Cast",
      },
      {
        mal_id: 57,
        type: "anime",
        name: "Gag Humor",
        url: "https://myanimelist.net/anime/genre/57/Gag_Humor",
      },
      {
        mal_id: 19,
        type: "anime",
        name: "Music",
        url: "https://myanimelist.net/anime/genre/19/Music",
      },
      {
        mal_id: 20,
        type: "anime",
        name: "Parody",
        url: "https://myanimelist.net/anime/genre/20/Parody",
      },
      {
        mal_id: 75,
        type: "anime",
        name: "Showbiz",
        url: "https://myanimelist.net/anime/genre/75/Showbiz",
      },
    ],
  },
  {
    mal_id: 4224,
    url: "https://myanimelist.net/anime/4224/Toradora",
    image: "https://cdn.myanimelist.net/images/anime/13/22128l.jpg",
    title: "Toradora!",
    title_english: "Toradora!",
    title_japanese: "とらドラ！",
    title_synonyms: ["Tiger X Dragon"],
    type: "TV",
    episodes: 25,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2008-10-02T00:00:00+00:00",
      to: "2009-03-26T00:00:00+00:00",
      prop: {
        from: {
          day: 2,
          month: 10,
          year: 2008,
        },
        to: {
          day: 26,
          month: 3,
          year: 2009,
        },
      },
      string: "Oct 2, 2008 to Mar 26, 2009",
    },
    score: 8.06,
    rank: 563,
    popularity: 25,
    synopsis:
      'Ryuuji Takasu is a gentle high school student with a love for housework; but in contrast to his kind nature, he has an intimidating face that often gets him labeled as a delinquent. On the other hand is Taiga Aisaka, a small, doll-like student, who is anything but a cute and fragile girl. Equipped with a wooden katana and feisty personality, Taiga is known throughout the school as the "Palmtop Tiger."\n\nOne day, an embarrassing mistake causes the two students to cross paths. Ryuuji discovers that Taiga actually has a sweet side: she has a crush on the popular vice president, Yuusaku Kitamura, who happens to be his best friend. But things only get crazier when Ryuuji reveals that he has a crush on Minori Kushieda—Taiga\'s best friend!\n\nToradora! is a romantic comedy that follows this odd duo as they embark on a quest to help each other with their respective crushes, forming an unlikely alliance in the process.\n\n[Written by MAL Rewrite]',
    year: 2008,
    genres: [
      {
        mal_id: 8,
        type: "anime",
        name: "Drama",
        url: "https://myanimelist.net/anime/genre/8/Drama",
      },
      {
        mal_id: 22,
        type: "anime",
        name: "Romance",
        url: "https://myanimelist.net/anime/genre/22/Romance",
      },
    ],
    themes: [
      {
        mal_id: 64,
        type: "anime",
        name: "Love Polygon",
        url: "https://myanimelist.net/anime/genre/64/Love_Polygon",
      },
      {
        mal_id: 23,
        type: "anime",
        name: "School",
        url: "https://myanimelist.net/anime/genre/23/School",
      },
    ],
  },
  {
    mal_id: 39535,
    url: "https://myanimelist.net/anime/39535/Mushoku_Tensei__Isekai_Ittara_Honki_Dasu",
    image: "https://cdn.myanimelist.net/images/anime/1530/117776l.jpg",
    title: "Mushoku Tensei: Isekai Ittara Honki Dasu",
    title_english: "Mushoku Tensei: Jobless Reincarnation",
    title_japanese: "無職転生 ～異世界行ったら本気だす～",
    title_synonyms: ["Jobless Reincarnation: I Will Seriously Try If I Go To Another World"],
    type: "TV",
    episodes: 11,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2021-01-11T00:00:00+00:00",
      to: "2021-03-22T00:00:00+00:00",
      prop: {
        from: {
          day: 11,
          month: 1,
          year: 2021,
        },
        to: {
          day: 22,
          month: 3,
          year: 2021,
        },
      },
      string: "Jan 11, 2021 to Mar 22, 2021",
    },
    score: 8.36,
    rank: 224,
    popularity: 96,
    synopsis:
      "Despite being bullied, scorned, and oppressed all of his life, a 34-year-old shut-in still found the resolve to attempt something heroic—only for it to end in a tragic accident. But in a twist of fate, he awakens in another world as Rudeus Greyrat, starting life again as a baby born to two loving parents.\n\nPreserving his memories and knowledge from his previous life, Rudeus quickly adapts to his new environment. With the mind of a grown adult, he starts to display magical talent that exceeds all expectations, honing his skill with the help of a mage named Roxy Migurdia. Rudeus learns swordplay from his father, Paul, and meets Sylphiette, a girl his age who quickly becomes his closest friend.\n\nAs Rudeus' second chance at life begins, he tries to make the most of his new opportunity while conquering his traumatic past. And perhaps, one day, he may find the one thing he could not find in his old world—love.\n\n[Written by MAL Rewrite]",
    year: 2021,
    genres: [
      {
        mal_id: 2,
        type: "anime",
        name: "Adventure",
        url: "https://myanimelist.net/anime/genre/2/Adventure",
      },
      {
        mal_id: 8,
        type: "anime",
        name: "Drama",
        url: "https://myanimelist.net/anime/genre/8/Drama",
      },
      {
        mal_id: 10,
        type: "anime",
        name: "Fantasy",
        url: "https://myanimelist.net/anime/genre/10/Fantasy",
      },
      {
        mal_id: 9,
        type: "anime",
        name: "Ecchi",
        url: "https://myanimelist.net/anime/genre/9/Ecchi",
      },
    ],
    themes: [
      {
        mal_id: 62,
        type: "anime",
        name: "Isekai",
        url: "https://myanimelist.net/anime/genre/62/Isekai",
      },
      {
        mal_id: 72,
        type: "anime",
        name: "Reincarnation",
        url: "https://myanimelist.net/anime/genre/72/Reincarnation",
      },
    ],
  },
  {
    mal_id: 11577,
    url: "https://myanimelist.net/anime/11577/Steins_Gate_Movie__Fuka_Ryouiki_no_Déjà_vu",
    image: "https://cdn.myanimelist.net/images/anime/1611/112806l.jpg",
    title: "Steins;Gate Movie: Fuka Ryouiki no Déjà vu",
    title_english: "Steins;Gate: The Movie - Load Region of Déjà Vu",
    title_japanese: "劇場版 シュタインズゲート 負荷領域のデジャヴ",
    title_synonyms: ["Steins Gate Movie"],
    type: "Movie",
    episodes: 1,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2013-04-20T00:00:00+00:00",
      to: null,
      prop: {
        from: {
          day: 20,
          month: 4,
          year: 2013,
        },
        to: {
          day: null,
          month: null,
          year: null,
        },
      },
      string: "Apr 20, 2013",
    },
    score: 8.45,
    rank: 166,
    popularity: 374,
    synopsis:
      "After a year in America, Kurisu Makise returns to Akihabara and reunites with Rintarou Okabe. However, their reunion is cut short when Okabe begins to experience recurring flashes of other timelines as the consequences of his time traveling start to manifest. These side effects eventually culminate in Okabe suddenly vanishing from the world, and only the startled Kurisu has any memory of his existence.\n\nIn the midst of despair, Kurisu is faced with a truly arduous choice that will test both her duty as a scientist and her loyalty as a friend: follow Okabe's advice and stay away from traveling through time to avoid the potential consequences it may have on the world lines, or ignore it to rescue the person that she cherishes most. Regardless of her decision, the path she chooses is one that will affect the past, the present, and the future.\n\n[Written by MAL Rewrite]",
    year: null,
    genres: [
      {
        mal_id: 8,
        type: "anime",
        name: "Drama",
        url: "https://myanimelist.net/anime/genre/8/Drama",
      },
      {
        mal_id: 24,
        type: "anime",
        name: "Sci-Fi",
        url: "https://myanimelist.net/anime/genre/24/Sci-Fi",
      },
    ],
  },
  {
    mal_id: 10162,
    url: "https://myanimelist.net/anime/10162/Usagi_Drop",
    image: "https://cdn.myanimelist.net/images/anime/1460/98853l.jpg",
    title: "Usagi Drop",
    title_english: "Bunny Drop",
    title_japanese: "うさぎドロップ",
    title_synonyms: ["Usagi Drop"],
    type: "TV",
    episodes: 11,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2011-07-08T00:00:00+00:00",
      to: "2011-09-16T00:00:00+00:00",
      prop: {
        from: {
          day: 8,
          month: 7,
          year: 2011,
        },
        to: {
          day: 16,
          month: 9,
          year: 2011,
        },
      },
      string: "Jul 8, 2011 to Sep 16, 2011",
    },
    score: 8.33,
    rank: 242,
    popularity: 462,
    synopsis:
      "Daikichi Kawachi is a 30-year-old bachelor working a respectable job but otherwise wandering aimlessly through life. When his grandfather suddenly passes away, he returns to the family home to pay his respects. Upon arriving at the house, he meets a mysterious young girl named Rin who, to Daikichi's astonishment, is his grandfather's illegitimate daughter!\n \nThe shy and unapproachable girl is deemed an embarrassment to the family, and finds herself ostracized by her father's relatives, all of them refusing to take care of her in the wake of his death. Daikichi, angered by their coldness toward Rin, announces that he will take her in—despite the fact that he is a young, single man with no prior childcare experience.\n\nUsagi Drop is the story of Daikichi's journey through fatherhood as he raises Rin with his gentle and affectionate nature, as well as an exploration of the warmth and interdependence that are at the heart of a happy, close-knit family.\n\n[Written by MAL Rewrite]",
    year: 2011,
    genres: [
      {
        mal_id: 36,
        type: "anime",
        name: "Slice of Life",
        url: "https://myanimelist.net/anime/genre/36/Slice_of_Life",
      },
    ],
  },
  {
    mal_id: 11111,
    url: "https://myanimelist.net/anime/11111/Another",
    image: "https://cdn.myanimelist.net/images/anime/4/75509l.jpg",
    title: "Another",
    title_english: "Another",
    title_japanese: "アナザー",
    title_synonyms: [],
    type: "TV",
    episodes: 12,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2012-01-10T00:00:00+00:00",
      to: "2012-03-27T00:00:00+00:00",
      prop: {
        from: {
          day: 10,
          month: 1,
          year: 2012,
        },
        to: {
          day: 27,
          month: 3,
          year: 2012,
        },
      },
      string: "Jan 10, 2012 to Mar 27, 2012",
    },
    score: 7.47,
    rank: 2007,
    popularity: 59,
    synopsis:
      "In class 3-3 of Yomiyama North Junior High, transfer student Kouichi Sakakibara makes his return after taking a sick leave for the first month of school. Among his new classmates, he is inexplicably drawn toward Mei Misaki—a reserved girl with an eyepatch whom he met in the hospital during his absence. But none of his classmates acknowledge her existence; they warn him not to acquaint himself with things that do not exist. Against their words of caution, Kouichi befriends Mei—soon learning of the sinister truth behind his friends' apprehension.\n\nThe ominous rumors revolve around a former student of the class 3-3. However, no one will share the full details of the grim event with Kouichi. Engrossed in the curse that plagues his class, Kouichi sets out to discover its connection to his new friend. As a series of tragedies arise around them, it is now up to Kouichi, Mei, and their classmates to unravel the eerie mystery—but doing so will come at a hefty price.\n\n[Written by MAL Rewrite]",
    year: 2012,
    genres: [
      {
        mal_id: 14,
        type: "anime",
        name: "Horror",
        url: "https://myanimelist.net/anime/genre/14/Horror",
      },
      {
        mal_id: 7,
        type: "anime",
        name: "Mystery",
        url: "https://myanimelist.net/anime/genre/7/Mystery",
      },
    ],
    themes: [
      {
        mal_id: 58,
        type: "anime",
        name: "Gore",
        url: "https://myanimelist.net/anime/genre/58/Gore",
      },
      {
        mal_id: 23,
        type: "anime",
        name: "School",
        url: "https://myanimelist.net/anime/genre/23/School",
      },
    ],
  },
  {
    mal_id: 13759,
    url: "https://myanimelist.net/anime/13759/Sakura-sou_no_Pet_na_Kanojo",
    image: "https://cdn.myanimelist.net/images/anime/4/43643l.jpg",
    title: "Sakura-sou no Pet na Kanojo",
    title_english: "The Pet Girl of Sakurasou",
    title_japanese: "さくら荘のペットな彼女",
    title_synonyms: ["Sakurasou no Pet na Kanojo"],
    type: "TV",
    episodes: 24,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "2012-10-09T00:00:00+00:00",
      to: "2013-03-26T00:00:00+00:00",
      prop: {
        from: {
          day: 9,
          month: 10,
          year: 2012,
        },
        to: {
          day: 26,
          month: 3,
          year: 2013,
        },
      },
      string: "Oct 9, 2012 to Mar 26, 2013",
    },
    score: 8.06,
    rank: 579,
    popularity: 108,
    synopsis:
      "At Suimei High, the Sakura-sou dormitory is infamous for housing the school's most notorious delinquents. Thus, when the relatively tame Sorata Kanda is transferred to the dorm, escaping this insane asylum becomes his foremost goal. Trapped there for the time being, he must learn how to deal with his fellow residents, including bubbly animator Misaki Kamiigusa, charming playboy writer Jin Mitaka, and the ever-reclusive Ryuunosuke Akasaka. Surrounded by weirdness, Sorata frequently finds respite in his interactions with his one \"normal\" friend, aspiring voice actress Nanami Aoyama.\n\nWhen Mashiro Shiina—a new foreign exchange student—joins the dormitory, Sorata is instantly enraptured by her beauty. Underneath her otherworldly appearance, Mashiro is an autistic savant, capable of world-renowned brilliance in her art, yet unable to perform simple daily tasks. After Sorata ends up in charge of taking care of Mashiro, the two inevitably grow closer, with Sorata's initial desire to escape the dormitory becoming a forgotten goal.\n\nDespite their eccentricities, every resident is incredible in their own field, leaving Sorata to contend with his own lack of any particular skill. With brilliance all around him, he thus strives to become an equal to their talent. Revolving around the hardships and joys of its colorful cast, Sakura-sou no Pet na Kanojo is a heartwarming coming-of-age tale of friendship, love, ambition, and heartbreak—through the lens of an ordinary person surrounded by the extraordinary.\n\n[Written by MAL Rewrite]",
    year: 2012,
    genres: [
      {
        mal_id: 8,
        type: "anime",
        name: "Drama",
        url: "https://myanimelist.net/anime/genre/8/Drama",
      },
      {
        mal_id: 22,
        type: "anime",
        name: "Romance",
        url: "https://myanimelist.net/anime/genre/22/Romance",
      },
    ],
    themes: [
      {
        mal_id: 23,
        type: "anime",
        name: "School",
        url: "https://myanimelist.net/anime/genre/23/School",
      },
      {
        mal_id: 80,
        type: "anime",
        name: "Visual Arts",
        url: "https://myanimelist.net/anime/genre/80/Visual_Arts",
      },
    ],
  },
  {
    mal_id: 30,
    url: "https://myanimelist.net/anime/30/Shinseiki_Evangelion",
    image: "https://cdn.myanimelist.net/images/anime/1314/108941l.jpg",
    title: "Shinseiki Evangelion",
    title_english: "Neon Genesis Evangelion",
    title_japanese: "新世紀エヴァンゲリオン",
    title_synonyms: ["NGE", "Evangelion (1995)"],
    type: "TV",
    episodes: 26,
    status: "Finished Airing",
    airing: false,
    aired: {
      from: "1995-10-04T00:00:00+00:00",
      to: "1996-03-27T00:00:00+00:00",
      prop: {
        from: {
          day: 4,
          month: 10,
          year: 1995,
        },
        to: {
          day: 27,
          month: 3,
          year: 1996,
        },
      },
      string: "Oct 4, 1995 to Mar 27, 1996",
    },
    score: 8.35,
    rank: 231,
    popularity: 45,
    synopsis:
      "Fifteen years after a cataclysmic event known as the Second Impact, the world faces a new threat: monstrous celestial beings called Angels invade Tokyo-3 one by one. Mankind is unable to defend themselves against the Angels despite utilizing their most advanced munitions and military tactics. The only hope for human salvation rests in the hands of NERV, a mysterious organization led by the cold Gendou Ikari. NERV operates giant humanoid robots dubbed \"Evangelions\" to combat the Angels with state-of-the-art advanced weaponry and protective barriers known as Absolute Terror Fields.\n\nYears after being abandoned by his father, Shinji Ikari, Gendou's 14-year-old son, returns to Tokyo-3. Shinji undergoes a perpetual internal battle against the deeply buried trauma caused by the loss of his mother and the emotional neglect he suffered at the hands of his father. Terrified to open himself up to another, Shinji's life is forever changed upon meeting 29-year-old Misato Katsuragi, a high-ranking NERV officer who shows him a free-spirited maternal kindness he has never experienced.\n\nA devastating Angel attack forces Shinji into action as Gendou reveals his true motive for inviting his son back to Tokyo-3: Shinji is the only child capable of efficiently piloting Evangelion Unit-01, a new robot that synchronizes with his biometrics. Despite the brutal psychological trauma brought about by piloting an Evangelion, Shinji defends Tokyo-3 against the angelic threat, oblivious to his father's dark machinations.\n\n[Written by MAL Rewrite]",
    year: 1995,
    genres: [
      {
        mal_id: 1,
        type: "anime",
        name: "Action",
        url: "https://myanimelist.net/anime/genre/1/Action",
      },
      {
        mal_id: 5,
        type: "anime",
        name: "Avant Garde",
        url: "https://myanimelist.net/anime/genre/5/Avant_Garde",
      },
      {
        mal_id: 46,
        type: "anime",
        name: "Award Winning",
        url: "https://myanimelist.net/anime/genre/46/Award_Winning",
      },
      {
        mal_id: 8,
        type: "anime",
        name: "Drama",
        url: "https://myanimelist.net/anime/genre/8/Drama",
      },
      {
        mal_id: 24,
        type: "anime",
        name: "Sci-Fi",
        url: "https://myanimelist.net/anime/genre/24/Sci-Fi",
      },
      {
        mal_id: 41,
        type: "anime",
        name: "Suspense",
        url: "https://myanimelist.net/anime/genre/41/Suspense",
      },
    ],
    themes: [
      {
        mal_id: 18,
        type: "anime",
        name: "Mecha",
        url: "https://myanimelist.net/anime/genre/18/Mecha",
      },
      {
        mal_id: 40,
        type: "anime",
        name: "Psychological",
        url: "https://myanimelist.net/anime/genre/40/Psychological",
      },
    ],
  },
]

const mangaData: MalFullMangaResponse[] = [
  {
    mal_id: 14893,
    url: "https://myanimelist.net/manga/14893/Monogatari_Series__First_Season",
    image: "https://cdn.myanimelist.net/images/manga/2/279887l.jpg",
    title: "Monogatari Series: First Season",
    title_english: null,
    title_japanese: "〈物語〉シリーズ ファーストシーズン",
    title_synonyms: [
      "Bakemonogatari",
      "Monster Tale",
      "Kizumonogatari",
      "Wound Tale",
      "Nisemonogatari",
      "Fake Tale",
      "Nekomonogatari: Kuro",
      "Nekomonogatari: Black",
    ],
    type: "Light Novel",
    chapters: 107,
    volumes: 6,
    status: "Finished",
    publishing: false,
    published: {
      from: "2006-11-01T00:00:00+00:00",
      to: "2010-07-28T00:00:00+00:00",
      prop: {
        from: {
          day: 1,
          month: 11,
          year: 2006,
        },
        to: {
          day: 28,
          month: 7,
          year: 2010,
        },
      },
      string: "Nov 1, 2006 to Jul 28, 2010",
    },
    score: 8.91,
    rank: 19,
    popularity: 276,
    synopsis:
      'This is a story, a "ghostory" of sorts, about scars that bond, monsters that haunt, and fakes that deceive.\n\nThe story of Koyomi Araragi begins through a fateful encounter with the all-powerful, blonde-haired, "hot-blooded, iron-blooded, and cold-blooded" vampire, later introduced as Shinobu Oshino. Their tragic rendezvous results in the end of Araragi\'s life as a human and his subsequent rebirth as a vampire—a monster. However, this encounter is only the start of his meddlings with the supernatural. Koyomi\'s noble personality ultimately sees him getting further involved in the lives of others with supernatural afflictions. This is his desperate attempt at returning to a normal human life, in a paranormal world filled with nothing but tragedy, suffering, and inhumanity.\n\n[Written by MAL Rewrite]\n\nThis entry includes the first season of the Monogatari Series.',
    genres: [
      {
        mal_id: 1,
        type: "manga",
        name: "Action",
        url: "https://myanimelist.net/manga/genre/1/Action",
      },
      {
        mal_id: 4,
        type: "manga",
        name: "Comedy",
        url: "https://myanimelist.net/manga/genre/4/Comedy",
      },
      {
        mal_id: 7,
        type: "manga",
        name: "Mystery",
        url: "https://myanimelist.net/manga/genre/7/Mystery",
      },
      {
        mal_id: 22,
        type: "manga",
        name: "Romance",
        url: "https://myanimelist.net/manga/genre/22/Romance",
      },
      {
        mal_id: 37,
        type: "manga",
        name: "Supernatural",
        url: "https://myanimelist.net/manga/genre/37/Supernatural",
      },
    ],
    themes: [
      {
        mal_id: 32,
        type: "manga",
        name: "Vampire",
        url: "https://myanimelist.net/manga/genre/32/Vampire",
      },
    ],
    year: 2006,
  },
  {
    mal_id: 28533,
    url: "https://myanimelist.net/manga/28533/Watashi_ga_Motenai_no_wa_Dou_Kangaetemo_Omaera_ga_Warui",
    image: "https://cdn.myanimelist.net/images/manga/5/63521l.jpg",
    title: "Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui!",
    title_english: "No Matter How I Look at It, It's You Guys' Fault I'm Not Popular!",
    title_japanese: "私がモテないのはどう考えてもお前らが悪い!",
    title_synonyms: [
      "WataMote",
      "Watashi ga Motenai no wa Dou Kangaete mo Omaera ga Warui!",
      "It's Not My Fault That I'm Not Popular!",
    ],
    type: "Manga",
    chapters: null,
    volumes: null,
    status: "Publishing",
    publishing: true,
    published: {
      from: "2011-08-04T00:00:00+00:00",
      to: null,
      prop: {
        from: {
          day: 4,
          month: 8,
          year: 2011,
        },
        to: {
          day: null,
          month: null,
          year: null,
        },
      },
      string: "Aug 4, 2011 to ?",
    },
    score: 7.73,
    rank: 1585,
    popularity: 297,
    synopsis:
      "Tomoko Kuroki is not cool. She is unattractive, socially awkward, and spends most of her evenings playing video games. Even so, no one wants popularity as desperately as she does. With one ingenious idea after another, Tomoko comes ever closer to achieving her goal—or so she thinks. Utilizing such innovative methods as imitating popular anime personas and buying expensive panties, she claws her way toward attaining the social status of her dreams.\n\nPathetically hilarious and strangely charming, Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui! depicts Tomoko's daily struggles with social anxiety in a lighthearted and relatable way.\n\n[Written by MAL Rewrite]",
    genres: [
      {
        mal_id: 4,
        type: "manga",
        name: "Comedy",
        url: "https://myanimelist.net/manga/genre/4/Comedy",
      },
    ],
    themes: [
      {
        mal_id: 70,
        type: "manga",
        name: "Otaku Culture",
        url: "https://myanimelist.net/manga/genre/70/Otaku_Culture",
      },
      {
        mal_id: 23,
        type: "manga",
        name: "School",
        url: "https://myanimelist.net/manga/genre/23/School",
      },
    ],
    year: 2011,
  },
  {
    mal_id: 7149,
    url: "https://myanimelist.net/manga/7149/Toradora",
    image: "https://cdn.myanimelist.net/images/manga/1/148447l.jpg",
    title: "Toradora!",
    title_english: "Toradora!",
    title_japanese: "とらドラ!",
    title_synonyms: [],
    type: "Light Novel",
    chapters: 62,
    volumes: 10,
    status: "Finished",
    publishing: false,
    published: {
      from: "2006-03-10T00:00:00+00:00",
      to: "2009-03-10T00:00:00+00:00",
      prop: {
        from: {
          day: 10,
          month: 3,
          year: 2006,
        },
        to: {
          day: 10,
          month: 3,
          year: 2009,
        },
      },
      string: "Mar 10, 2006 to Mar 10, 2009",
    },
    score: 8.21,
    rank: 409,
    popularity: 665,
    synopsis:
      "Takasu Ryuuji might look like a thug, but he's actually a nice guy. Making friends when you've got an unintentionally scary face is tough—and don't even get him started on girlfriends. But with his secret crush in his class, the start of his second year of high school is off to a good start...until he crosses paths with Aisaka Taiga. Beautiful, frightening, and not quite five feet tall, the girl known as the Palmtop Tiger is the one person in school even scarier than Ryuuji himself—and he's just made the mistake of making her very, very angry.\n\n(Source: Seven Seas Entertainment)",
    genres: [
      {
        mal_id: 8,
        type: "manga",
        name: "Drama",
        url: "https://myanimelist.net/manga/genre/8/Drama",
      },
      {
        mal_id: 22,
        type: "manga",
        name: "Romance",
        url: "https://myanimelist.net/manga/genre/22/Romance",
      },
    ],
    themes: [
      {
        mal_id: 64,
        type: "manga",
        name: "Love Polygon",
        url: "https://myanimelist.net/manga/genre/64/Love_Polygon",
      },
      {
        mal_id: 23,
        type: "manga",
        name: "School",
        url: "https://myanimelist.net/manga/genre/23/School",
      },
    ],
    year: 2006,
  },
  {
    mal_id: 102997,
    url: "https://myanimelist.net/manga/102997/Saotome_Senshu_Hitakakusu",
    image: "https://cdn.myanimelist.net/images/manga/1/189746l.jpg",
    title: "Saotome Senshu, Hitakakusu",
    title_english: null,
    title_japanese: "早乙女選手、ひたかくす",
    title_synonyms: [],
    type: "Manga",
    chapters: 124,
    volumes: 10,
    status: "Finished",
    publishing: false,
    published: {
      from: "2016-08-22T00:00:00+00:00",
      to: "2019-10-21T00:00:00+00:00",
      prop: {
        from: {
          day: 22,
          month: 8,
          year: 2016,
        },
        to: {
          day: 21,
          month: 10,
          year: 2019,
        },
      },
      string: "Aug 22, 2016 to Oct 21, 2019",
    },
    score: 7.48,
    rank: 3094,
    popularity: 631,
    synopsis:
      "Satoru Tsukishima has just been confessed to by fellow high school boxing club member Yae Saotome, who is currently the Kanto region's Female Featherweight Champion. Overjoyed at first, Satoru isn't able to accept her feelings as he believes that she should be focusing on boxing instead. Yae's championship will soon be on the line, and the entire school is counting on her to someday represent Tokyo in the Olympics. It also doesn't help that he's nowhere near as skilled as she is, conflicted by the thought of a rising star being in a relationship with someone as average as him.\n\nBut when their coach finds out about the confession, Satoru is assigned as Yae's trainer so the two can secretly date and spend more time together while also engaging in club activities. However, if anyone finds out about the two, it will mean the end of their relationship. With this in mind, their pure and awkward romance begins!\n\n[Written by MAL Rewrite]",
    genres: [
      {
        mal_id: 4,
        type: "manga",
        name: "Comedy",
        url: "https://myanimelist.net/manga/genre/4/Comedy",
      },
      {
        mal_id: 22,
        type: "manga",
        name: "Romance",
        url: "https://myanimelist.net/manga/genre/22/Romance",
      },
      {
        mal_id: 30,
        type: "manga",
        name: "Sports",
        url: "https://myanimelist.net/manga/genre/30/Sports",
      },
    ],
    themes: [
      {
        mal_id: 54,
        type: "manga",
        name: "Combat Sports",
        url: "https://myanimelist.net/manga/genre/54/Combat_Sports",
      },
      {
        mal_id: 23,
        type: "manga",
        name: "School",
        url: "https://myanimelist.net/manga/genre/23/School",
      },
    ],
    year: 2016,
  },
  {
    mal_id: 31,
    url: "https://myanimelist.net/manga/31/Lovely★Complex",
    image: "https://cdn.myanimelist.net/images/manga/1/209659l.jpg",
    title: "Lovely★Complex",
    title_english: "Love★Com",
    title_japanese: "ラブ★コン",
    title_synonyms: ["Love Com Plus", "Lovely Complex Plus"],
    type: "Manga",
    chapters: 68,
    volumes: 17,
    status: "Finished",
    publishing: false,
    published: {
      from: "2001-08-13T00:00:00+00:00",
      to: "2007-08-13T00:00:00+00:00",
      prop: {
        from: {
          day: 13,
          month: 8,
          year: 2001,
        },
        to: {
          day: 13,
          month: 8,
          year: 2007,
        },
      },
      string: "Aug 13, 2001 to Aug 13, 2007",
    },
    score: 8.32,
    rank: 285,
    popularity: 254,
    synopsis:
      "When the taller than average 172 cm Risa Koizumi learns that her occasional nemesis, the shorter than average 156 cm Atsushi Ootani, is romantically interested in her friend, she decides to team up with him. After all, she also has feelings for his friend. Unluckily, however, their respective crushes fall for each other instead. Determined to find new love after their recent misfortunes, the pair decide to cheer each other on while maintaining their usual dynamic of constant bickering. \n\nAlthough they continually deny it, Risa and Ootani are more similar than they like to admit: they both have unusual heights, failing grades, identical tastes in food, and a tendency to act extremely childish. Together, they inspire laughter among their peers as a so-called comedic duo. Could the love that these two are looking for be closer than they think?\n\n[Written by MAL Rewrite]\n\n\nIncluded one-shots:\nVolume 12: Hoshi ni Nattemo Aishiteru\nVolume 16: Bokura no Ibasho",
    genres: [
      {
        mal_id: 46,
        type: "manga",
        name: "Award Winning",
        url: "https://myanimelist.net/manga/genre/46/Award_Winning",
      },
      {
        mal_id: 4,
        type: "manga",
        name: "Comedy",
        url: "https://myanimelist.net/manga/genre/4/Comedy",
      },
      {
        mal_id: 8,
        type: "manga",
        name: "Drama",
        url: "https://myanimelist.net/manga/genre/8/Drama",
      },
      {
        mal_id: 22,
        type: "manga",
        name: "Romance",
        url: "https://myanimelist.net/manga/genre/22/Romance",
      },
    ],
    themes: [
      {
        mal_id: 23,
        type: "manga",
        name: "School",
        url: "https://myanimelist.net/manga/genre/23/School",
      },
    ],
    year: 2001,
  },
  {
    mal_id: 109339,
    url: "https://myanimelist.net/manga/109339/Saihate_no_Paladin",
    image: "https://cdn.myanimelist.net/images/manga/2/208057l.jpg",
    title: "Saihate no Paladin",
    title_english: "The Faraway Paladin",
    title_japanese: "最果てのパラディン",
    title_synonyms: ["Paladin of the End", "Ultimate Paladin"],
    type: "Manga",
    chapters: null,
    volumes: null,
    status: "Publishing",
    publishing: true,
    published: {
      from: "2017-09-25T00:00:00+00:00",
      to: null,
      prop: {
        from: {
          day: 25,
          month: 9,
          year: 2017,
        },
        to: {
          day: null,
          month: null,
          year: null,
        },
      },
      string: "Sep 25, 2017 to ?",
    },
    score: 7.8,
    rank: 1293,
    popularity: 611,
    synopsis:
      "William is the lone human in a city of the dead. Born with vague memories of a past life in contemporary Japan where he failed to do anything useful, he is determined not to make the same mistake again, and that this time, his life will be lived. But what does that really mean? Raised by a group of the undead, William must discover what circumstances brought him to this city and these people as well as what it means to not just exist, but to live a full life.\n\n(Source: ANN)",
    genres: [
      {
        mal_id: 1,
        type: "manga",
        name: "Action",
        url: "https://myanimelist.net/manga/genre/1/Action",
      },
      {
        mal_id: 2,
        type: "manga",
        name: "Adventure",
        url: "https://myanimelist.net/manga/genre/2/Adventure",
      },
      {
        mal_id: 10,
        type: "manga",
        name: "Fantasy",
        url: "https://myanimelist.net/manga/genre/10/Fantasy",
      },
    ],
    themes: [
      {
        mal_id: 62,
        type: "manga",
        name: "Isekai",
        url: "https://myanimelist.net/manga/genre/62/Isekai",
      },
      {
        mal_id: 73,
        type: "manga",
        name: "Reincarnation",
        url: "https://myanimelist.net/manga/genre/73/Reincarnation",
      },
    ],
    year: 2017,
  },
  {
    mal_id: 113010,
    url: "https://myanimelist.net/manga/113010/Bakemonogatari",
    image: "https://cdn.myanimelist.net/images/manga/2/210355l.jpg",
    title: "Bakemonogatari",
    title_english: "Bakemonogatari",
    title_japanese: "化物語",
    title_synonyms: ["Monster Tale", "Monogatari Series: First Season"],
    type: "Manga",
    chapters: 193,
    volumes: 22,
    status: "Finished",
    publishing: false,
    published: {
      from: "2018-03-14T00:00:00+00:00",
      to: "2023-03-15T00:00:00+00:00",
      prop: {
        from: {
          day: 14,
          month: 3,
          year: 2018,
        },
        to: {
          day: 15,
          month: 3,
          year: 2023,
        },
      },
      string: "Mar 14, 2018 to Mar 15, 2023",
    },
    score: 8.49,
    rank: 153,
    popularity: 462,
    synopsis:
      "Koyomi Araragi is no stranger to the abnormal. During the spring break of his third year in high school, a fateful encounter with vampire Kiss-Shot Acerola-Orion Heart-Under-Blade turns him into a vampire himself. Thrust into the world of oddities, Araragi finds himself catching classmate Hitagi Senjougahara when she falls down the school stairs one day—but something is amiss. After being confronted by the girl in question, Araragi learns that her weight was stolen by a mythical crab. In spite of Senjougahara's blunt threats, he manages to convince her to let him help. In need of a solution to an abnormal problem, the two visit the mysterious Meme Oshino, a wanderer who saved Araragi from his vampirism.\n\nBakemonogatari is a tale about the monsters that reside within everyone, but just how deep do they dwell in the people Araragi meets?\n\n[Written by MAL Rewrite]",
    genres: [
      {
        mal_id: 1,
        type: "manga",
        name: "Action",
        url: "https://myanimelist.net/manga/genre/1/Action",
      },
      {
        mal_id: 4,
        type: "manga",
        name: "Comedy",
        url: "https://myanimelist.net/manga/genre/4/Comedy",
      },
      {
        mal_id: 8,
        type: "manga",
        name: "Drama",
        url: "https://myanimelist.net/manga/genre/8/Drama",
      },
      {
        mal_id: 7,
        type: "manga",
        name: "Mystery",
        url: "https://myanimelist.net/manga/genre/7/Mystery",
      },
      {
        mal_id: 22,
        type: "manga",
        name: "Romance",
        url: "https://myanimelist.net/manga/genre/22/Romance",
      },
      {
        mal_id: 37,
        type: "manga",
        name: "Supernatural",
        url: "https://myanimelist.net/manga/genre/37/Supernatural",
      },
    ],
    themes: [
      {
        mal_id: 32,
        type: "manga",
        name: "Vampire",
        url: "https://myanimelist.net/manga/genre/32/Vampire",
      },
    ],
    year: 2018,
  },
  {
    mal_id: 37707,
    url: "https://myanimelist.net/manga/37707/Shigatsu_wa_Kimi_no_Uso",
    image: "https://cdn.myanimelist.net/images/manga/3/102691l.jpg",
    title: "Shigatsu wa Kimi no Uso",
    title_english: "Your Lie in April",
    title_japanese: "四月は君の嘘",
    title_synonyms: [],
    type: "Manga",
    chapters: 44,
    volumes: 11,
    status: "Finished",
    publishing: false,
    published: {
      from: "2011-04-06T00:00:00+00:00",
      to: "2015-02-06T00:00:00+00:00",
      prop: {
        from: {
          day: 6,
          month: 4,
          year: 2011,
        },
        to: {
          day: 6,
          month: 2,
          year: 2015,
        },
      },
      string: "Apr 6, 2011 to Feb 6, 2015",
    },
    score: 8.59,
    rank: 99,
    popularity: 192,
    synopsis:
      'At a very young age, Kousei Arima was strictly taught how to play the piano and meticulously follow the score by his mother, to the point where he dominated every competition he entered with ease. He earned the title of "Human Metronome" for performing almost perfectly. Every musician of his age looked up to him. However, after his mother suddenly dies, he became tone-deaf due to the shock and then disappeared, never to be seen onstage since.\n\nTwo years later, Kousei lives a monotonous life with his childhood friends Tsubaki Sawabe and Ryouta Watari supporting him. He continues to cling to music, although performing is still an impossibility for him. This is until his unexpected encounter with Kaori Miyazono, a violinist who performs freely without the dictations of a score. A story of friendship, love, music, and a single lie, Kousei\'s life begins to change and gain color as Kaori helps him to take up music again.\n\n[Written by MAL Rewrite]',
    genres: [
      {
        mal_id: 46,
        type: "manga",
        name: "Award Winning",
        url: "https://myanimelist.net/manga/genre/46/Award_Winning",
      },
      {
        mal_id: 8,
        type: "manga",
        name: "Drama",
        url: "https://myanimelist.net/manga/genre/8/Drama",
      },
      {
        mal_id: 22,
        type: "manga",
        name: "Romance",
        url: "https://myanimelist.net/manga/genre/22/Romance",
      },
    ],
    themes: [
      {
        mal_id: 19,
        type: "manga",
        name: "Music",
        url: "https://myanimelist.net/manga/genre/19/Music",
      },
      {
        mal_id: 23,
        type: "manga",
        name: "School",
        url: "https://myanimelist.net/manga/genre/23/School",
      },
    ],
    year: 2011,
  },
  {
    mal_id: 419,
    url: "https://myanimelist.net/manga/419/Nodame_Cantabile",
    image: "https://cdn.myanimelist.net/images/manga/2/153962l.jpg",
    title: "Nodame Cantabile",
    title_english: "Nodame Cantabile",
    title_japanese: "のだめカンタービレ",
    title_synonyms: ["Nodame Cantabile: Encore Opera-hen", "Nodame Cantabile Backstage"],
    type: "Manga",
    chapters: 150,
    volumes: 25,
    status: "Finished",
    publishing: false,
    published: {
      from: "2001-07-10T00:00:00+00:00",
      to: "2010-08-25T00:00:00+00:00",
      prop: {
        from: {
          day: 10,
          month: 7,
          year: 2001,
        },
        to: {
          day: 25,
          month: 8,
          year: 2010,
        },
      },
      string: "Jul 10, 2001 to Aug 25, 2010",
    },
    score: 8.4,
    rank: 213,
    popularity: 661,
    synopsis:
      'Shinichi Chiaki, the perfectionist son of a famous pianist, is in his fourth year at Momogaoka College of Music, hoping to achieve his secret dream of being a conductor. His admiration for his father led him to pursue a career in music. As much as he wants to return to Europe, his phobia of flying traps him in Japan where he now lives.\n\nOne night, he passes out, and ends up being taken in by Megumi "Nodame" Noda. Upon first glance, Nodame is a talented pianist, but she is also slobbish and eccentric. What\'s even worse is that she is his neighbor and he ends up forced to work with her. Though it sounds like a recipe for disaster, Chiaki is drawn to this girl who makes him remember the love for music he once held. Just what does the future hold for this musical duo?\n\n[Written by MAL Rewrite]',
    genres: [
      {
        mal_id: 46,
        type: "manga",
        name: "Award Winning",
        url: "https://myanimelist.net/manga/genre/46/Award_Winning",
      },
      {
        mal_id: 4,
        type: "manga",
        name: "Comedy",
        url: "https://myanimelist.net/manga/genre/4/Comedy",
      },
      {
        mal_id: 22,
        type: "manga",
        name: "Romance",
        url: "https://myanimelist.net/manga/genre/22/Romance",
      },
      {
        mal_id: 36,
        type: "manga",
        name: "Slice of Life",
        url: "https://myanimelist.net/manga/genre/36/Slice_of_Life",
      },
    ],
    themes: [
      {
        mal_id: 50,
        type: "manga",
        name: "Adult Cast",
        url: "https://myanimelist.net/manga/genre/50/Adult_Cast",
      },
      {
        mal_id: 19,
        type: "manga",
        name: "Music",
        url: "https://myanimelist.net/manga/genre/19/Music",
      },
    ],
    year: 2001,
  },
  {
    mal_id: 21,
    url: "https://myanimelist.net/manga/21/Death_Note",
    image: "https://cdn.myanimelist.net/images/manga/1/258245l.jpg",
    title: "Death Note",
    title_english: "Death Note",
    title_japanese: "DEATH NOTE",
    title_synonyms: [],
    type: "Manga",
    chapters: 108,
    volumes: 12,
    status: "Finished",
    publishing: false,
    published: {
      from: "2003-12-01T00:00:00+00:00",
      to: "2006-05-15T00:00:00+00:00",
      prop: {
        from: {
          day: 1,
          month: 12,
          year: 2003,
        },
        to: {
          day: 15,
          month: 5,
          year: 2006,
        },
      },
      string: "Dec 1, 2003 to May 15, 2006",
    },
    score: 8.69,
    rank: 60,
    popularity: 13,
    synopsis:
      'Ryuk, a god of death, drops his Death Note into the human world for personal pleasure. In Japan, prodigious high school student Light Yagami stumbles upon it. Inside the notebook, he finds a chilling message: those whose names are written in it shall die. Its nonsensical nature amuses Light; but when he tests its power by writing the name of a criminal in it, they suddenly meet their demise.\n\nRealizing the Death Note\'s vast potential, Light commences a series of nefarious murders under the pseudonym "Kira," vowing to cleanse the world of corrupt individuals and create a perfect society where crime ceases to exist. However, the police quickly catch on, and they enlist the help of L—a mastermind detective—to uncover the culprit.\n\nDeath Note tells the thrilling tale of Light and L as they clash in a great battle-of-minds, one that will determine the future of the world.\n\n[Written by MAL Rewrite]',
    genres: [
      {
        mal_id: 37,
        type: "manga",
        name: "Supernatural",
        url: "https://myanimelist.net/manga/genre/37/Supernatural",
      },
      {
        mal_id: 45,
        type: "manga",
        name: "Suspense",
        url: "https://myanimelist.net/manga/genre/45/Suspense",
      },
    ],
    themes: [
      {
        mal_id: 40,
        type: "manga",
        name: "Psychological",
        url: "https://myanimelist.net/manga/genre/40/Psychological",
      },
    ],
    year: 2003,
  },
]

const characterData: CharacterFavorites[] = [
  {
    mal_id: 22037,
    url: "https://myanimelist.net/character/22037/Hitagi_Senjougahara",
    image: "https://cdn.myanimelist.net/images/characters/11/287902.jpg?s=559b750212c5338e987b3d0ebac9d810",
    name: "Senjougahara, Hitagi",
  },
  {
    mal_id: 1185,
    url: "https://myanimelist.net/character/1185/Megumi_Noda",
    image: "https://cdn.myanimelist.net/images/characters/11/92497.jpg?s=f8d450c55e9f47ee9b6cb93c9cb5a098",
    name: "Noda, Megumi",
  },
  {
    mal_id: 12064,
    url: "https://myanimelist.net/character/12064/Taiga_Aisaka",
    image: "https://cdn.myanimelist.net/images/characters/11/514086.jpg?s=87920301db499bb344d2efd437699bc4",
    name: "Aisaka, Taiga",
  },
  {
    mal_id: 153859,
    url: "https://myanimelist.net/character/153859/Yae_Saotome",
    image: "https://cdn.myanimelist.net/images/characters/12/538425.jpg?s=6fcca0ca41d34078b13f35c57dd80804",
    name: "Saotome, Yae",
  },
  {
    mal_id: 50057,
    url: "https://myanimelist.net/character/50057/Tomoko_Kuroki",
    image: "https://cdn.myanimelist.net/images/characters/15/212635.jpg?s=d3756e5ae6e0e0f03736ba6f464227a2",
    name: "Kuroki, Tomoko",
  },
  {
    mal_id: 22054,
    url: "https://myanimelist.net/character/22054/Suruga_Kanbaru",
    image: "https://cdn.myanimelist.net/images/characters/11/222449.jpg?s=807b29db48805d06f863451ae8b44d27",
    name: "Kanbaru, Suruga",
  },
  {
    mal_id: 6977,
    url: "https://myanimelist.net/character/6977/Sawako_Kuronuma",
    image: "https://cdn.myanimelist.net/images/characters/6/120945.jpg?s=b66012c0e8676ef7a444e429ed06e184",
    name: "Kuronuma, Sawako",
  },
  {
    mal_id: 674,
    url: "https://myanimelist.net/character/674/Kagura",
    image: "https://cdn.myanimelist.net/images/characters/2/245933.jpg?s=a256c2fb147ac3e58818f69eb7e9fe8c",
    name: "Kagura",
  },
]

const peopleData: PeopleFavorites[] = [
  {
    mal_id: 2,
    url: "https://myanimelist.net/people/2/Tomokazu_Sugita",
    image: "https://cdn.myanimelist.net/images/voiceactors/1/81054.jpg?s=acb8e1dcacacc3d869c36ec876c8c4da",
    name: "Sugita, Tomokazu",
  },
  {
    mal_id: 118,
    url: "https://myanimelist.net/people/118/Hiroshi_Kamiya",
    image: "https://cdn.myanimelist.net/images/voiceactors/1/66163.jpg?s=cb07743b7325f20adaa7921160f73646",
    name: "Kamiya, Hiroshi",
  },
  {
    mal_id: 7899,
    url: "https://myanimelist.net/people/7899/Izumi_Kitta",
    image: "https://cdn.myanimelist.net/images/voiceactors/1/55656.jpg?s=1aec911b4fc352baf988ed06c83ff3d1",
    name: "Kitta, Izumi",
  },
  {
    mal_id: 99,
    url: "https://myanimelist.net/people/99/Miyuki_Sawashiro",
    image: "https://cdn.myanimelist.net/images/voiceactors/2/65500.jpg?s=80c733f0aefed4b574d900e2a4a9037e",
    name: "Sawashiro, Miyuki",
  },
  {
    mal_id: 4875,
    url: "https://myanimelist.net/people/4875/Yuyuko_Takemiya",
    image: "https://cdn.myanimelist.net/images/voiceactors/3/60414.jpg?s=23363b3bbe0dbcf21cafbde02441454b",
    name: "Takemiya, Yuyuko",
  },
  {
    mal_id: 1904,
    url: "https://myanimelist.net/people/1904/Hideaki_Sorachi",
    image: "https://cdn.myanimelist.net/images/voiceactors/1/44890.jpg?s=cf786139b5b5f43206e017497fbaa765",
    name: "Sorachi, Hideaki",
  },
  {
    mal_id: 13,
    url: "https://myanimelist.net/people/13/Ayako_Kawasumi",
    image: "https://cdn.myanimelist.net/images/voiceactors/2/69419.jpg?s=19f702c4cf0e2e0b44e125f8bc9511ab",
    name: "Kawasumi, Ayako",
  },
  {
    mal_id: 8,
    url: "https://myanimelist.net/people/8/Rie_Kugimiya",
    image: "https://cdn.myanimelist.net/images/voiceactors/3/63374.jpg?s=afa01c0ce80060bd11daeb6e220679c4",
    name: "Kugimiya, Rie",
  },
  {
    mal_id: 61,
    url: "https://myanimelist.net/people/61/Chiwa_Saitou",
    image: "https://cdn.myanimelist.net/images/voiceactors/3/79603.jpg?s=0fdc6450e4421d1f182b6c6223723df5",
    name: "Saitou, Chiwa",
  },
  {
    mal_id: 5254,
    url: "https://myanimelist.net/people/5254/ISIN_NISIO",
    image: "https://cdn.myanimelist.net/images/voiceactors/2/43583.jpg?s=d5875b3197c6226978d5eeac7a473f2d",
    name: "NISIO, ISIN",
  },
]

const fakeData: {
  animes: FullMalAnimeResponse[]
  characters: CharacterFavorites[]
  mangas: MalFullMangaResponse[]
  people: PeopleFavorites[]
  updates: MalLastUpdatesResponse
} = {
  animes: faker.helpers.arrayElements(animeData, { min: 10, max: 20 }),
  characters: faker.helpers.arrayElements(characterData, { min: 10, max: 20 }),
  mangas: faker.helpers.arrayElements(mangaData, { min: 10, max: 20 }),
  people: faker.helpers.arrayElements(peopleData, { min: 10, max: 20 }),
  updates: {
    anime: faker.helpers.arrayElements(animeData, { min: 10, max: 20 }).map((anime) => ({
      episodes_seen: faker.number.int({ min: 0, max: anime.episodes ?? 12 }),
      episodes_total: anime.episodes,
      score: faker.number.int({ min: 0, max: 10 }),
      status: faker.helpers.arrayElement(["Watching", "Completed", "On hold", "Dropped", "Plan to Watch"]),
      entry: anime,
      date: new Date().toISOString(),
    })),
    manga: faker.helpers.arrayElements(mangaData, { min: 10, max: 20 }).map((manga) => ({
      chapters_seen: faker.number.int({ min: 0, max: manga.chapters ?? 12 }),
      chapters_total: manga.chapters,
      chapters_read: faker.number.int({ min: 0, max: manga.chapters ?? 100 }),
      score: faker.number.int({ min: 0, max: 10 }),
      status: faker.helpers.arrayElement(["Reading", "Completed", "On hold", "Dropped", "Plan to Read"]),
      entry: manga,
      date: new Date().toISOString(),
    })),
  },
}

export default fakeData
