#!/usr/bin/env tsx
/**
 * Gera docs/plugins.md: galeria de todas as seções de todos os plugins,
 * nos estilos default e terminal, usando os previews estáticos já commitados
 * em weeb-dashboard/public/previews/.
 *
 * Depende de weeb-plugins/scripts/generate-preview-images.ts +
 * generate-section-previews.ts já terem sido rodados (os previews precisam
 * existir em weeb-dashboard/public/previews/ e weeb-dashboard/lib/config/section-previews.ts
 * precisa estar atualizado).
 *
 * Execute: pnpm generate-plugins-doc (no root)
 */

import * as fs from "fs"
import * as path from "path"
import { fileURLToPath } from "url"
import { dirname } from "path"
import { PLUGINS_METADATA } from "../weeb-plugins/src/plugins/metadata.js"
import { SECTION_PREVIEWS } from "../weeb-dashboard/lib/config/section-previews.js"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const ROOT_DIR = path.join(__dirname, "..")
const OUTPUT_FILE = path.join(ROOT_DIR, "docs/plugins.md")

// Caminho relativo de docs/plugins.md até weeb-dashboard/public/previews/
const PREVIEWS_REL_PATH = "../weeb-dashboard/public/previews"

function sectionTable(pluginName: string, sections: string[], style: "default" | "terminal"): string {
  const rows = sections
    .map((sectionId) => {
      const info = SECTION_PREVIEWS[pluginName]?.[sectionId]
      const hasStyle = info?.[style]
      const imgSrc = hasStyle
        ? `${PREVIEWS_REL_PATH}/${pluginName}/${style}/${sectionId}.svg`
        : `${PREVIEWS_REL_PATH}/${pluginName}/default/${sectionId}.svg`
      return `    <tr>\n      <td><code>${sectionId}</code></td>\n      <td><img src="${imgSrc}" width="415"></td>\n    </tr>`
    })
    .join("\n")

  return `  <table>\n    <tr>\n      <td align="center">Section</td>\n      <td align="center" width="415px">${style === "default" ? "Default" : "Terminal"} Style</td>\n    </tr>\n${rows}\n  </table>`
}

function main() {
  const pluginNames = Object.keys(SECTION_PREVIEWS).sort()

  const tocEntries = pluginNames
    .map((name) => {
      const displayName = (PLUGINS_METADATA as Record<string, any>)[name]?.displayName || name
      return `- [${displayName}](#${name.toLowerCase()})`
    })
    .join("\n")

  const pluginSections = pluginNames
    .map((pluginName) => {
      const metadata = (PLUGINS_METADATA as Record<string, any>)[pluginName]
      const displayName = metadata?.displayName || pluginName
      const description = metadata?.description || ""
      const sections = Object.keys(SECTION_PREVIEWS[pluginName])

      return `<details close>
  <summary><b>${displayName}</b></summary>

${description ? `${description}\n` : ""}
### Default Style

${sectionTable(pluginName, sections, "default")}

### Terminal Style

${sectionTable(pluginName, sections, "terminal")}

</details>`
    })
    .join("\n\n")

  const totalSections = pluginNames.reduce((sum, name) => sum + Object.keys(SECTION_PREVIEWS[name]).length, 0)

  const content = `<!-- AUTO-GENERATED by scripts/generate-plugins-doc.ts, run "pnpm generate-plugins-doc" to update -->

# Galeria de plugins e seções

Todos os plugins do WeebProfile e as seções disponíveis para cada um, nos estilos \`default\` e \`terminal\`.
Essas imagens são geradas com dados de exemplo (mock) pelo mesmo \`svg-generator\` usado em produção — ${totalSections} seções ao todo.

Pra usar de verdade, acesse o [dashboard](https://weebprofile-dashboard.pages.dev), escolha as seções que quiser e cole o markdown gerado no seu README.

## Plugins

${tocEntries}

---

${pluginSections}
`

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
  fs.writeFileSync(OUTPUT_FILE, content, "utf-8")
  console.log(`✅ docs/plugins.md gerado em: ${OUTPUT_FILE}`)
  console.log(`   Plugins: ${pluginNames.length}, Seções: ${totalSections}`)
}

main()
