/**
 * GraphQL Queries para GitHub API
 */
export declare const PROFILE_QUERY = "\nquery userProfile($login: String!) {\n  user(login: $login) {\n    name\n    login\n    avatarUrl\n    createdAt\n    followers {\n      totalCount\n    }\n    following {\n      totalCount\n    }\n    contributionsCollection {\n      contributionCalendar {\n        totalContributions\n        weeks {\n          contributionDays {\n            color\n            contributionCount\n            date\n          }\n        }\n      }\n    }\n    repositoriesContributedTo {\n      totalCount\n    }\n  }\n}\n";
export declare const CALENDAR_QUERY = "\nquery userCalendar($login: String!, $from: DateTime, $to: DateTime) {\n  user(login: $login) {\n    contributionsCollection(from: $from, to: $to) {\n      contributionCalendar {\n        totalContributions\n        weeks {\n          contributionDays {\n            color\n            contributionCount\n            date\n            weekday\n          }\n        }\n      }\n    }\n  }\n}\n";
export declare const ACTIVITY_QUERY = "\nquery userActivity($login: String!) {\n  user(login: $login) {\n    contributionsCollection {\n      totalCommitContributions\n      totalRepositoriesWithContributedCommits\n      totalPullRequestContributions\n      totalPullRequestReviewContributions\n      totalIssueContributions\n      restrictedContributionsCount\n    }\n    repositoriesContributedTo(includeUserRepositories: true) {\n      totalCount\n    }\n    issueComments {\n      totalCount\n    }\n    organizations {\n      totalCount\n    }\n    following {\n      totalCount\n    }\n    sponsorshipsAsSponsor {\n      totalCount\n    }\n    starredRepositories {\n      totalCount\n    }\n    watching {\n      totalCount\n    }\n    pullRequests(states: OPEN) {\n      totalCount\n    }\n    issues(states: OPEN) {\n      totalCount\n    }\n    gists {\n      totalCount\n    }\n    projects {\n      totalCount\n    }\n  }\n}\n";
export declare const LANGUAGES_QUERY = "\nquery userLanguages($login: String!) {\n  user(login: $login) {\n    repositories(\n      first: 100\n      ownerAffiliations: [OWNER]\n      isFork: false\n      orderBy: { field: UPDATED_AT, direction: DESC }\n    ) {\n      nodes {\n        languages(first: 10, orderBy: { field: SIZE, direction: DESC }) {\n          edges {\n            size\n            node {\n              name\n              color\n            }\n          }\n        }\n      }\n    }\n  }\n}\n";
export declare const REPOSITORIES_QUERY = "\nquery userRepositories($login: String!, $privacy: RepositoryPrivacy) {\n  user(login: $login) {\n    repositories(\n      first: 100\n      ownerAffiliations: [OWNER]\n      isFork: false\n      orderBy: { field: UPDATED_AT, direction: DESC }\n      privacy: $privacy\n    ) {\n      nodes {\n        updatedAt\n        name\n        description\n        url\n        owner {\n          login\n        }\n        isFork\n        forkCount\n        watchers {\n          totalCount\n        }\n        stargazers {\n          totalCount\n        }\n        releases {\n          totalCount\n        }\n        deployments {\n          totalCount\n        }\n        environments {\n          totalCount\n        }\n        languages(first: 8) {\n          edges {\n            size\n            node {\n              color\n              name\n            }\n          }\n        }\n        licenseInfo {\n          name\n          spdxId\n        }\n        issues_open: issues(states: OPEN) {\n          totalCount\n        }\n        issues_closed: issues(states: CLOSED) {\n          totalCount\n        }\n        pr_open: pullRequests(states: OPEN) {\n          totalCount\n        }\n        pr_closed: pullRequests(states: CLOSED) {\n          totalCount\n        }\n        pr_merged: pullRequests(states: MERGED) {\n          totalCount\n        }\n      }\n      totalDiskUsage\n    }\n    contributionsCollection {\n      totalCommitContributions\n      totalRepositoriesWithContributedCommits\n      totalIssueContributions\n      totalPullRequestContributions\n      totalPullRequestReviewContributions\n    }\n  }\n}\n";
export declare const STARRED_REPOSITORIES_QUERY = "\nquery userStarredRepositories($login: String!) {\n  user(login: $login) {\n    starredRepositories(first: 20, orderBy: {field: STARRED_AT, direction: DESC}) {\n      totalCount\n      nodes {\n        name\n        nameWithOwner\n        description\n        url\n        stargazerCount\n        forkCount\n        primaryLanguage {\n          name\n          color\n        }\n        updatedAt\n      }\n    }\n  }\n}\n";
export declare const GISTS_QUERY = "\nquery userGists($login: String!) {\n  user(login: $login) {\n    gists(first: 20, orderBy: {field: UPDATED_AT, direction: DESC}) {\n      totalCount\n      nodes {\n        name\n        description\n        url\n        files {\n          name\n          language {\n            name\n          }\n        }\n        updatedAt\n        stargazerCount\n      }\n    }\n  }\n}\n";
export declare const TOP_REPOSITORIES_QUERY = "\nquery userTopRepositories($login: String!) {\n  user(login: $login) {\n    topRepositories(first: 10, orderBy: {field: STARGAZERS, direction: DESC}) {\n      nodes {\n        name\n        nameWithOwner\n        description\n        url\n        stargazerCount\n        forkCount\n        primaryLanguage {\n          name\n          color\n        }\n        updatedAt\n      }\n    }\n  }\n}\n";
export declare const INTRODUCTION_QUERY = "\nquery userIntroduction($login: String!) {\n  user(login: $login) {\n    bio\n    location\n    company\n    websiteUrl\n    twitterUsername\n  }\n}\n";
export declare const RECENT_ACTIVITY_QUERY = "\nquery userRecentActivity($login: String!) {\n  user(login: $login) {\n    contributionsCollection {\n      commitContributionsByRepository(maxRepositories: 10) {\n        repository {\n          name\n          nameWithOwner\n          url\n        }\n        contributions {\n          totalCount\n        }\n      }\n    }\n  }\n}\n";
export declare const SPONSORSHIPS_QUERY = "\nquery userSponsorships($login: String!) {\n  user(login: $login) {\n    sponsorshipsAsSponsor(first: 20) {\n      totalCount\n      nodes {\n        sponsorable {\n          ... on User {\n            login\n            name\n            avatarUrl\n          }\n          ... on Organization {\n            login\n            name\n            avatarUrl\n          }\n        }\n        tier {\n          name\n          monthlyPriceInDollars\n        }\n      }\n    }\n  }\n}\n";
export declare const SPONSORS_QUERY = "\nquery userSponsors($login: String!) {\n  user(login: $login) {\n    sponsors(first: 20) {\n      totalCount\n      nodes {\n        ... on User {\n          login\n          name\n          avatarUrl\n        }\n        ... on Organization {\n          login\n          name\n          avatarUrl\n        }\n      }\n    }\n  }\n}\n";
export declare const FOLLOWERS_QUERY = "\nquery userFollowers($login: String!, $max: Int!) {\n  user(login: $login) {\n    followers(first: $max) {\n      totalCount\n      nodes {\n        login\n        name\n        avatarUrl\n      }\n    }\n  }\n}\n";
export declare const REPOSITORY_CONTRIBUTORS_QUERY = "\nquery repositoryContributors($owner: String!, $repo: String!) {\n  repository(owner: $owner, name: $repo) {\n    defaultBranchRef {\n      target {\n        ... on Commit {\n          history(first: 100) {\n            nodes {\n              author {\n                user {\n                  login\n                  name\n                  avatarUrl\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n";
export declare const REPOSITORY_STARGAZERS_QUERY = "\nquery repositoryStargazers($owner: String!, $repo: String!, $max: Int!) {\n  repository(owner: $owner, name: $repo) {\n    stargazers(first: $max) {\n      totalCount\n      nodes {\n        login\n        name\n        avatarUrl\n      }\n    }\n  }\n}\n";
export declare const REPOSITORY_WATCHERS_QUERY = "\nquery repositoryWatchers($owner: String!, $repo: String!, $max: Int!) {\n  repository(owner: $owner, name: $repo) {\n    watchers(first: $max) {\n      totalCount\n      nodes {\n        login\n        name\n        avatarUrl\n      }\n    }\n  }\n}\n";
export declare const FEATURED_REPOSITORIES_QUERY = "\nquery featuredRepositories($owner: String!, $repo: String!) {\n  repository(owner: $owner, name: $repo) {\n    name\n    nameWithOwner\n    description\n    url\n    createdAt\n    stargazerCount\n    forkCount\n    issues {\n      totalCount\n    }\n    pullRequests {\n      totalCount\n    }\n    primaryLanguage {\n      name\n      color\n    }\n    licenseInfo {\n      name\n      spdxId\n    }\n  }\n}\n";
export declare const SECTION_QUERIES: {
    readonly profile: "\nquery userProfile($login: String!) {\n  user(login: $login) {\n    name\n    login\n    avatarUrl\n    createdAt\n    followers {\n      totalCount\n    }\n    following {\n      totalCount\n    }\n    contributionsCollection {\n      contributionCalendar {\n        totalContributions\n        weeks {\n          contributionDays {\n            color\n            contributionCount\n            date\n          }\n        }\n      }\n    }\n    repositoriesContributedTo {\n      totalCount\n    }\n  }\n}\n";
    readonly repositories: "\nquery userRepositories($login: String!, $privacy: RepositoryPrivacy) {\n  user(login: $login) {\n    repositories(\n      first: 100\n      ownerAffiliations: [OWNER]\n      isFork: false\n      orderBy: { field: UPDATED_AT, direction: DESC }\n      privacy: $privacy\n    ) {\n      nodes {\n        updatedAt\n        name\n        description\n        url\n        owner {\n          login\n        }\n        isFork\n        forkCount\n        watchers {\n          totalCount\n        }\n        stargazers {\n          totalCount\n        }\n        releases {\n          totalCount\n        }\n        deployments {\n          totalCount\n        }\n        environments {\n          totalCount\n        }\n        languages(first: 8) {\n          edges {\n            size\n            node {\n              color\n              name\n            }\n          }\n        }\n        licenseInfo {\n          name\n          spdxId\n        }\n        issues_open: issues(states: OPEN) {\n          totalCount\n        }\n        issues_closed: issues(states: CLOSED) {\n          totalCount\n        }\n        pr_open: pullRequests(states: OPEN) {\n          totalCount\n        }\n        pr_closed: pullRequests(states: CLOSED) {\n          totalCount\n        }\n        pr_merged: pullRequests(states: MERGED) {\n          totalCount\n        }\n      }\n      totalDiskUsage\n    }\n    contributionsCollection {\n      totalCommitContributions\n      totalRepositoriesWithContributedCommits\n      totalIssueContributions\n      totalPullRequestContributions\n      totalPullRequestReviewContributions\n    }\n  }\n}\n";
    readonly activity: "\nquery userActivity($login: String!) {\n  user(login: $login) {\n    contributionsCollection {\n      totalCommitContributions\n      totalRepositoriesWithContributedCommits\n      totalPullRequestContributions\n      totalPullRequestReviewContributions\n      totalIssueContributions\n      restrictedContributionsCount\n    }\n    repositoriesContributedTo(includeUserRepositories: true) {\n      totalCount\n    }\n    issueComments {\n      totalCount\n    }\n    organizations {\n      totalCount\n    }\n    following {\n      totalCount\n    }\n    sponsorshipsAsSponsor {\n      totalCount\n    }\n    starredRepositories {\n      totalCount\n    }\n    watching {\n      totalCount\n    }\n    pullRequests(states: OPEN) {\n      totalCount\n    }\n    issues(states: OPEN) {\n      totalCount\n    }\n    gists {\n      totalCount\n    }\n    projects {\n      totalCount\n    }\n  }\n}\n";
    readonly calendar: "\nquery userCalendar($login: String!, $from: DateTime, $to: DateTime) {\n  user(login: $login) {\n    contributionsCollection(from: $from, to: $to) {\n      contributionCalendar {\n        totalContributions\n        weeks {\n          contributionDays {\n            color\n            contributionCount\n            date\n            weekday\n          }\n        }\n      }\n    }\n  }\n}\n";
    readonly favorite_languages: "\nquery userLanguages($login: String!) {\n  user(login: $login) {\n    repositories(\n      first: 100\n      ownerAffiliations: [OWNER]\n      isFork: false\n      orderBy: { field: UPDATED_AT, direction: DESC }\n    ) {\n      nodes {\n        languages(first: 10, orderBy: { field: SIZE, direction: DESC }) {\n          edges {\n            size\n            node {\n              name\n              color\n            }\n          }\n        }\n      }\n    }\n  }\n}\n";
    readonly favorite_license: "\nquery userRepositories($login: String!, $privacy: RepositoryPrivacy) {\n  user(login: $login) {\n    repositories(\n      first: 100\n      ownerAffiliations: [OWNER]\n      isFork: false\n      orderBy: { field: UPDATED_AT, direction: DESC }\n      privacy: $privacy\n    ) {\n      nodes {\n        updatedAt\n        name\n        description\n        url\n        owner {\n          login\n        }\n        isFork\n        forkCount\n        watchers {\n          totalCount\n        }\n        stargazers {\n          totalCount\n        }\n        releases {\n          totalCount\n        }\n        deployments {\n          totalCount\n        }\n        environments {\n          totalCount\n        }\n        languages(first: 8) {\n          edges {\n            size\n            node {\n              color\n              name\n            }\n          }\n        }\n        licenseInfo {\n          name\n          spdxId\n        }\n        issues_open: issues(states: OPEN) {\n          totalCount\n        }\n        issues_closed: issues(states: CLOSED) {\n          totalCount\n        }\n        pr_open: pullRequests(states: OPEN) {\n          totalCount\n        }\n        pr_closed: pullRequests(states: CLOSED) {\n          totalCount\n        }\n        pr_merged: pullRequests(states: MERGED) {\n          totalCount\n        }\n      }\n      totalDiskUsage\n    }\n    contributionsCollection {\n      totalCommitContributions\n      totalRepositoriesWithContributedCommits\n      totalIssueContributions\n      totalPullRequestContributions\n      totalPullRequestReviewContributions\n    }\n  }\n}\n";
    readonly starred_repositories: "\nquery userStarredRepositories($login: String!) {\n  user(login: $login) {\n    starredRepositories(first: 20, orderBy: {field: STARRED_AT, direction: DESC}) {\n      totalCount\n      nodes {\n        name\n        nameWithOwner\n        description\n        url\n        stargazerCount\n        forkCount\n        primaryLanguage {\n          name\n          color\n        }\n        updatedAt\n      }\n    }\n  }\n}\n";
    readonly gists: "\nquery userGists($login: String!) {\n  user(login: $login) {\n    gists(first: 20, orderBy: {field: UPDATED_AT, direction: DESC}) {\n      totalCount\n      nodes {\n        name\n        description\n        url\n        files {\n          name\n          language {\n            name\n          }\n        }\n        updatedAt\n        stargazerCount\n      }\n    }\n  }\n}\n";
    readonly top_repositories: "\nquery userTopRepositories($login: String!) {\n  user(login: $login) {\n    topRepositories(first: 10, orderBy: {field: STARGAZERS, direction: DESC}) {\n      nodes {\n        name\n        nameWithOwner\n        description\n        url\n        stargazerCount\n        forkCount\n        primaryLanguage {\n          name\n          color\n        }\n        updatedAt\n      }\n    }\n  }\n}\n";
    readonly introduction: "\nquery userIntroduction($login: String!) {\n  user(login: $login) {\n    bio\n    location\n    company\n    websiteUrl\n    twitterUsername\n  }\n}\n";
    readonly recent_activity: "\nquery userRecentActivity($login: String!) {\n  user(login: $login) {\n    contributionsCollection {\n      commitContributionsByRepository(maxRepositories: 10) {\n        repository {\n          name\n          nameWithOwner\n          url\n        }\n        contributions {\n          totalCount\n        }\n      }\n    }\n  }\n}\n";
    readonly sponsorships: "\nquery userSponsorships($login: String!) {\n  user(login: $login) {\n    sponsorshipsAsSponsor(first: 20) {\n      totalCount\n      nodes {\n        sponsorable {\n          ... on User {\n            login\n            name\n            avatarUrl\n          }\n          ... on Organization {\n            login\n            name\n            avatarUrl\n          }\n        }\n        tier {\n          name\n          monthlyPriceInDollars\n        }\n      }\n    }\n  }\n}\n";
    readonly sponsors: "\nquery userSponsors($login: String!) {\n  user(login: $login) {\n    sponsors(first: 20) {\n      totalCount\n      nodes {\n        ... on User {\n          login\n          name\n          avatarUrl\n        }\n        ... on Organization {\n          login\n          name\n          avatarUrl\n        }\n      }\n    }\n  }\n}\n";
};
