name: Check web-client code

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check web-client code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
      - name: Go to the web-client directory
        run: cd web-client
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint check
        run: yarn lint
      - name: Format check
        run: yarn prettier
