name: Check core code

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check core code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Print working directory
        working-directory: ./core
        run: pwd
      - name: Lint check
        working-directory: ./core
        run: yarn run lint
      - name: Format check
        working-directory: ./core
        run: yarn run prettier
